// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouBuJDsVYIY8Hmk7G-HsRMJkWnn_y1Gk',
    appId: '1:424491524575:web:a68eb3d057be9241dee46a',
    messagingSenderId: '424491524575',
    projectId: 'kicks-8f35e',
    authDomain: 'kicks-8f35e.firebaseapp.com',
    storageBucket: 'kicks-8f35e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh_j5cOUXH5AjYOUOTMb4ZHSgmhRyrgKM',
    appId: '1:424491524575:android:fc087158dece0eb5dee46a',
    messagingSenderId: '424491524575',
    projectId: 'kicks-8f35e',
    storageBucket: 'kicks-8f35e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ALCXdPFZuvjseNzLGVjJuuIOo4uf3V0',
    appId: '1:424491524575:ios:c54e2dfb34e1e7ffdee46a',
    messagingSenderId: '424491524575',
    projectId: 'kicks-8f35e',
    storageBucket: 'kicks-8f35e.appspot.com',
    androidClientId: '424491524575-qru8l5brju9609n8020b3rom01nmhdh2.apps.googleusercontent.com',
    iosClientId: '424491524575-qm410g817tbe3hcs2dl0d0hpuh5btn8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.kicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ALCXdPFZuvjseNzLGVjJuuIOo4uf3V0',
    appId: '1:424491524575:ios:501f6166dfc4ce41dee46a',
    messagingSenderId: '424491524575',
    projectId: 'kicks-8f35e',
    storageBucket: 'kicks-8f35e.appspot.com',
    androidClientId: '424491524575-qru8l5brju9609n8020b3rom01nmhdh2.apps.googleusercontent.com',
    iosClientId: '424491524575-6uphef1s18ovg3d9k536h3bceubjbgu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kicks.RunnerTests',
  );
}
